repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
 # Ruff version.
    rev: v0.5.1
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
